apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      serviceAccountName: myapp-service-account
      containers:
      - name: helm-variables
        image: grrywlsn/helm-variables:latest
        imagePullPolicy: Always
        env:
        - name: APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: APP_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONSUL_SERVICE_HOST
          value: "consul.service.zhq.consul"
        - name: CONSUL_SERVICE_PORT
          value: "8080"
        - name: CONSUL_TOKEN
          value: "zopa-app-readonly"
        - name: VAULT_SERVICE_HOST
          value: "10.244.5.15"
        - name: VAULT_SERVICE_PORT
          value: "8200"
        command:
          - sleep
          - "36000"
        volumeMounts:
        - name: source-volume
          mountPath: /source
      volumes:
      - name: source-volume
        emptyDir: {}
